version: '3.8'

services:

  db:
    image: mysql:5.7
    ports:
      - "${DB_LOCAL_PORT}:${DB_DOCKER_PORT}"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
